version: "3.8"

services:
  ethstats-server:
    build: .
    container_name: ethstats-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - proxy
    env_file:
      - ./.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.ethstats-server.entrypoints=http"
    #   - "traefik.http.routers.ethstats-server.rule=Host(`testnet-explorer.nuxify.tech`)"
    #   - "traefik.http.routers.ethstats-server-secure.entrypoints=https"
    #   - "traefik.http.routers.ethstats-server-secure.rule=Host(`testnet-explorer.nuxify.tech`)"
    #   - "traefik.http.routers.ethstats-server-secure.tls=true"
    #   - "traefik.http.routers.ethstats-server-secure.tls.certresolver=http"
    #   - "traefik.http.routers.ethstats-server-secure.service=ethstats-server"
    #   - "traefik.http.services.ethstats-server.loadbalancer.server.port=16000"
    #   - "traefik.docker.network=proxy"
    ports:
      - 17000:17000

networks:
  proxy:
    external: true

