services:
  ethstats-server:
    build: .
    container_name: ethstats-server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - proxy
    env_file:
      - ./.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ethstats-server.entrypoints=http"
      - "traefik.http.routers.ethstats-server.rule=Host(`testnet-ethstats.nuxify.tech`)"
      - "traefik.http.routers.ethstats-server-secure.entrypoints=https"
      - "traefik.http.routers.ethstats-server-secure.rule=Host(`testnet-ethstats.nuxify.tech`)"
      - "traefik.http.routers.ethstats-server-secure.tls=true"
      - "traefik.http.routers.ethstats-server-secure.tls.certresolver=http"
      - "traefik.http.routers.ethstats-server-secure.service=ethstats-server"
      - "traefik.http.services.ethstats-server.loadbalancer.server.port=17000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

